# Generated by Django 4.1.1 on 2022-09-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientes', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('pedido', models.CharField(max_length=50)),
                ('vendedor', models.CharField(max_length=50)),
                ('itens', models.CharField(max_length=50)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
